plugins {
	id 'java'
	alias libs.plugins.spring.boot.plugin
	alias libs.plugins.spring.boot.dependency.management.plugin
}

group = 'ru.florizzz'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation libs.spring.boot.starter.jooq
	implementation libs.spring.boot.starter.webmvc
	implementation libs.spring.doc
	developmentOnly libs.spring.dev.tools
	runtimeOnly libs.postgres.driver
	testImplementation libs.spring.boot.starter.jooq.test
	testImplementation libs.spring.boot.starter.webmvc.test
	testRuntimeOnly libs.junit.platform.launcher
}

tasks.named('test') {
	useJUnitPlatform()
}
